name: crop_image
description: An image cropper widget, with 90-degree rotations. Supports mobile, web and desktop.
version: 1.0.13
homepage: https://github.com/deakjahn/crop_image

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
